### ISSUE TITLE
Text inside Masthead component doesn't render as single line on iPhone SE screen size

### ISSUE THREAD

**Issue by jmalvinez** [GovTechSG/sgds-web-component#193]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-web-component/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-web-component/blob/master/CONTRIBUTING.md)

### Describe the issue

Hi team, the text inside the Masthead component doesn't render as a single line on iPhone SE screen size.

**Steps to reproduce**

1. On Chrome, go to [Masthead component in Storybook](https://www.webcomponent.designsystem.tech.gov.sg/?path=/story/components-masthead--basic).
2. Switch to iPhone SE screen size using Chrome dev tools.

**Expected behaviour**
Text inside Masthead component is rendered as a single line similar to the behaviour in the deprecated [@govtechsg/sgds-masthead-react package](https://www.npmjs.com/package/@govtechsg/sgds-masthead-react).

**Actual behaviour**
Text inside Masthead component is rendered as two lines.
![Masthead_iPhoneSE](https://github.com/GovTechSG/sgds-web-component/assets/19561463/1b9c2d89-dc44-4bd5-9cf4-d464d5f4dbf5)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-web-component are you using? CSR or SSR?

React v18.2.0, @govtechsg/sgds-web-component v1.0.2

**Comment by clukhei** [comment]
<img width="933" alt="Screenshot 2024-05-17 at 10 38 05 AM" src="https://github.com/GovTechSG/sgds-web-component/assets/55618945/01cf4dd6-ba18-463e-b0d1-0d9b00cb9602">

@jmalvinez  Hi I would say the masthead itself  does not have a bug. Its looking like that due to the additional padding from Storybook's default container padding. We will see what we can do to remove the container paddings in the documented page, but the component itself is working fine. See the screenshot above where i remove storybook's padding in iphone SE size

**Comment by clukhei** [comment]
Closing this as it will be fixed in the version 3 of storybook documentation
